package com.matiasborra.jokes.model.entity;
// Generated 2 may 2025, 20:13:38 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

import java.io.Serial;
import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language", schema = "public")
public class Language implements java.io.Serializable {

	@Serial
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	@Column(name = "code", length = 2)
	private String code;

	@Column(name = "language")
	private String language;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	private Set<Joke> jokeses = new HashSet<Joke>(0);

	public Language() {
	}

	public Language(long id) {
		this.id = id;
	}

	public Language(long id, String code, String language, Set<Joke> jokeses) {
		this.id = id;
		this.code = code;
		this.language = language;
		this.jokeses = jokeses;
	}

	public long getId() {
		return this.id;
	}
	public void setId(long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}
	public void setCode(String code) {
		this.code = code;
	}

	public String getLanguage() {
		return this.language;
	}
	public void setLanguage(String language) {
		this.language = language;
	}

	public Set<Joke> getJokeses() {
		return this.jokeses;
	}
	public void setJokeses(Set<Joke> jokeses) {
		this.jokeses = jokeses;
	}
}
